### PR TITLE
Currencies API

### LINKED ISSUE #5: Implement currencies API
- [ ] Fetch all supported currencies
- [ ] Fetch exchange rates

### PR DESCRIPTION
**Pull request by oneEyedSunday**
For, closes https://github.com/fluidcoins/client-go/issues/5

### CODE REVIEW

**Comment by oneEyedSunday** [comment]
I cant quite find a walk-through on providing a mock for the http client here to include tests in these PRs.

Basically i'm looking for a way to mock the http client embedded in the fluidcoins.Client so I can more easily make assertions against the url called and response. Not quite sure how this is done in golang (and also cant quite find open source SDKs that actually make these assertions, most jjust seem to actually make the call against a live server)

```golang
// currencies_test.go

package fluidcoins

import (
	"context"
	"net/http"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func Test_Currencies(t *testing.T) {
	h := &http.Client{
		Timeout: time.Minute * 20,
	}

       // need a way to provide a response here


	c, _ := New(HTTPClient(h), SecretKey("oo"))
	currs, resp, err := c.Currency.List(context.TODO(), &CurrencyListOptions{
		FilterTestNet: false,
	})

	require.NoError(t, err)
	require.Equal(t, currs, nil)
	require.Equal(t, resp, nil)
}


```


cc @adelowo

**Comment by adelowo** [comment]
@oneEyedSunday you can mock it by providing your own `*http.Server`. I haven't had time over the last few days but I will roll up mocks sometime next week

**Comment by adelowo** [comment]
@oneEyedSunday can we do this? set it up by default https://github.com/fluidcoins/client-go/blob/08ac3fd50dad3ab26d72e61c65d3db92314c26fc/fluidcoins/client.go#L72

PR looks very good

**Comment by oneEyedSunday** [comment]
Yh I figured, with your wrist and all

**Comment by oneEyedSunday** [comment]
Tests added in https://github.com/fluidcoins/client-go/pull/10/commits/62ed070d7d88533078a6080820da7345dbcceabe 

cc @adelowo 

That was a wild ride 😅

**Comment by adelowo** [comment]
hehe. taking a look later today boss

**Comment by adelowo** [comment]
@oneEyedSunday can you send me an email `lanre@fluidcoins.com`. I'd love to chat on how you can make and complete this package.

**Pull request merged**
